### ISSUE TITLE
squashfs

### ISSUE THREAD

**Issue by yangxiaoddddd** [zhangguanzhang/Installer#1]
大佬，cobbler引导squashfs时，pxelinux.cfg/default咋配置的

**Comment by zhangguanzhang** [comment]
cobbler没玩过，不过理论上差不多吧，我理解的是cobbler应该all in one了，只不过没硬件raid之类的

**Comment by yangxiaoddddd** [comment]
就是pxelinux引导squashfs.img时,咋配置的pxelinux.cfg/default文件KERNEL----APPEND那里，我不知道APPEND root=？

**Comment by zhangguanzhang** [comment]
因为设置了`bootfile-name BOOTX64.EFI`，这个是里面会叫客户端使用grub.cfg的，你看我文件 https://github.com/zhangguanzhang/Installer/blob/master/docker/tftp/grub.cfg.tmpl#L27
