### ISSUE TITLE
这个项目是不支持安装Ubuntu系统嘛?

### ISSUE THREAD

**Issue by liyuanjie8521** [zhangguanzhang/Installer#2]
我做过尝试安装ubuntu失败了. 作者是否可以开发一个兼容安装Ubuntu系统和提供web界面的新功能呢? 做到批量自动配置raid然后批量自动安装ubuntu系统和centos系统?  目前这个安装centos系统是可以的。但是安装ubuntu系统失败了.

**Comment by zhangguanzhang** [comment]
Ubuntu我记得pxe得单独去下载iso，我现在没条件和时间去测试Ubuntu的，你按照我的步骤测试过了吗，哪步有问题
