### ISSUE TITLE
./Installer -ks=template/ks.tmpl  ERROR

### ISSUE THREAD

**Issue by mikesiwer** [zhangguanzhang/Installer#5]
./Installer -ks=template/ks.tmpl  ERROR
FATA[0000] kickstart template file template/ks.tmpl stat template/ks.tmpl: no such file or directory

Anyone know how to fix this？
In Dir, all files are there

**Comment by zhangguanzhang** [comment]
dlv 调试下吧，我这个源码是仅供参考和思路的
```
ls -l
ls -l template
```
