### ISSUE TITLE
修正下文档中的一些打包initrd.img的参数问题

### ISSUE THREAD

**Issue by jimmy201602** [zhangguanzhang/Installer#6]
https://github.com/zhangguanzhang/Installer/blob/master/docs/linux-start.md#%E4%BF%AE%E6%94%B9initrdimg%E6%9C%89%E9%9C%80%E8%A6%81%E7%9A%84%E8%AF%9D 里
```
修改一些东西后下面是打包
$ find . -print0 | cpio --null --create --verbose --format=newc | gzip --best > ../myinitrd
```
修正为可以减少体积
```
find . |  cpio -o -c -R root:root | xz -3 --format=xz --check=crc32 > ../myinitrd.img
```

**Comment by zhangguanzhang** [comment]
文档的步骤经过我和网络上不认识的另外两个网友都试过，理论上你这个只是压缩后的容量更小了。如果有其他人遇到无法开机参考你的步骤解决了的话我改下文档，issue 先放着不关闭

**Comment by jimmy201602** [comment]
压缩方式而已，无需纠结！
